#!/bin/sh

echo "==============================" && \
echo "=====> libmp3lame installing..... " && \
echo "==============================" && \
DIR=$(mktemp -d) && cd ${DIR} && \
curl -sL https://downloads.sf.net/project/lame/lame/${LAME_VERSION%.*}/lame-${LAME_VERSION}.tar.gz | \
  tar -zx --strip-components=1 && \
./configure --prefix="${SRC}" --bindir="${SRC}/bin" --disable-static --enable-nasm --datarootdir="${DIR}" && \
make && \
make install && \
rm -rf ${DIR}